name       : haskell-yaml
version    : 0.8.22
release    : 1
source     :
    - http://hackage.haskell.org/package/yaml-0.8.22/yaml-0.8.22.tar.gz : 76429aedad04cadacbdc20fdb7f4a763b8e5bf9f733d6c97f166edb24bd9b5a3
license    : BSD-3-Clause
component  : programming.haskell
summary    : Provides support for parsing and emitting Yaml documents.
description: |
    Provides support for parsing and emitting Yaml documents.
builddeps  :
    - haskell-aeson
    - haskell-cabal-install
    - haskell-conduit
    - haskell-semigroups
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
