name       : haskell-yaml
version    : 0.11.4.0
release    : 3
source     :
    - https://hackage.haskell.org/package/yaml-0.11.4.0/yaml-0.11.4.0.tar.gz : da4ec8469bb5cc43d131ffee90e89a430a65baad4caa611e91cd9b684168c96c
license    : BSD-3-Clause
component  : programming.haskell
summary    : Provides support for parsing and emitting Yaml documents.
description: |
    Provides support for parsing and emitting Yaml documents.
builddeps  :
    - haskell-aeson-devel
    - haskell-cabal-install
    - haskell-libyaml-devel
rundeps    :
    - devel:
        - haskell-aeson-devel
        - haskell-libyaml-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
