name       : haskell-yaml
version    : 0.8.30
release    : 2
source     :
    - https://hackage.haskell.org/package/yaml-0.8.30/yaml-0.8.30.tar.gz : d15b6e9d599137329161931478259462549dd1a38337ec7e8b17fe1c3496be85
license    : BSD-3-Clause
component  : programming.haskell
summary    : Provides support for parsing and emitting Yaml documents.
description: |
    Provides support for parsing and emitting Yaml documents.
builddeps  :
    - haskell-aeson
    - haskell-cabal-install
    - haskell-conduit
    - haskell-semigroups
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
